[package]
name = "folley-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
folley-format = { path = "../format" }
defmt =  { version = "0.3.0", optional = true }

[features]
default = ["std"]
std = []
defmt_print = ["defmt"]